# Server configuration
server.port=8080

# Spring Doc configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database paths (JSON files)
booker.db.users-path=app/src/main/java/booker/localDb/user.json
booker.db.trains-path=app/src/main/java/booker/localDb/trains.json

# Jackson formatting
spring.jackson.serialization.indent_output=true
