/*
 * This source file was generated by the Gradle 'init' task
 */
package booker;

import booker.services.UserBookingService;

import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
    System.out.println("Running Train Booking System");
    Scanner scanner = new Scanner(System.in);
    int option =0;

        UserBookingService UserBookingService;

        try {
            UserBookingService =new UserBookingService();
        }catch(IOExpection ex){
            System.out.println("There is Something Wrong");
            return;
        }
        while(option!=7)

    }
}